knp_snappy:
    pdf:
        enabled: true
        binary: '%env(resolve:WKHTMLTOPDF_PATH)%'
        options:
            enable-local-file-access: true
            disable-smart-shrinking: true
            print-media-type: true
            margin-top: 10mm
            margin-bottom: 10mm
            margin-left: 10mm
            margin-right: 10mm
            zoom: 1
    image:
        enabled: true
        binary: '%env(resolve:WKHTMLTOIMAGE_PATH)%'
        options: []
