security:
    # 1) Hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2) Users
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3) Firewalls
    firewalls:
        # → API JSON stateless
        api:
            pattern:   ^/api-client
            security: false

            json_login:
                check_path:      /api-client/login
                username_path:   email
                password_path:   password
                success_handler: App\Security\ApiLoginSuccessHandler
                failure_handler: App\Security\ApiLoginFailureHandler

        # → Form login web classique
        main:
            pattern:   ^/
            provider:  app_user_provider
            lazy:      true

            form_login:
                login_path:       app_login
                check_path:       app_login
                enable_csrf:      true
                success_handler:  App\Security\LoginSuccessHandler

            logout:
                path:   app_logout
                target: app_login

            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 604800
                path:     /

    # 4) Contrôles d’accès
    access_control:
        # Autoriser le /api-client/login en anonyme (JSON)
        - { path: ^/api-client/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Protéger tout le reste de /api-client
        - { path: ^/api-client,        roles: IS_AUTHENTICATED_FULLY }

        # Vos règles web habituelles
        - { path: ^/admin,      roles: ROLE_ADMIN }
        - { path: ^/profile,    roles: ROLE_USER }
