controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_seats_by_room:
    path: /api/seats/room/{id}
    controller: App\Controller\Api\SeatApiController::byRoom
    methods: [GET]
