# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./public

jobs:
# Please do not rename this job
  build-project:
    name: build Cinephoria
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # if you add permissions here this needs to be done in the Cinephoria-orchestration.yaml as well
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/Cinephoria
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.14.0

      - name: Build Node assets
        env:
          APP_SECRET: a28624b90e0951d5ccf158a7f74256c40543c1b905b75378188f4dcbaed1d6f1
          CI: true
          DATABASE_URL: mysql://u14252629:Sid.jtm2813@db5017894454.hosting-data.io:3306/dbs14252629
          SITE_URL: ${{ inputs.site-url }}
        run: |
          yarn install
          yarn run build

      - name: Setup composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          tools: composer:2

      - name: Run composer install
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: composer install --optimize-autoloader --no-dev

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 955560a9-e379-4eb5-b22c-1a5f9307a1fe
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Cinephoria/config.yaml
          action: upload
